language: php

php:
  - 7.1.3
  - 7.2
  - 7.3

services:
  - postgresql

before_install:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp .env.travis .env
  - composer install
  - php artisan migrate

script: vendor/bin/phpunit
